### ISSUE TITLE
Uniqueness requirements for IDs could be clearer

### ISSUE THREAD

**Issue by RPrimrose** [graphql/graphql-spec#473]
Would it be possible for the description of IDs to make clearer that they're only required to be unique within a type, although some implementations may choose to make them globally unique? 

It's possible to read "The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache." as meaning that they're required to be globally unique. I think the lack of using a word like MUST/SHOULD/MAY from https://tools.ietf.org/html/rfc2119 contributes to this. 

(The reason I'm bringing this up is that a lot of older documentation/discussions on the web refer to them being required to be globally unique, I believe mostly because that used to be a requirement of Relay? I've been finding it confusing as I learn about GraphQL anyway and it would be great for the spec to be clearer on this 😄 )

**Comment by jlouis** [comment]
The main point of the `ID` type is to make it clear to clients they should not manipulate the reference. Were it a `String`, you might have clients interpreting that string and passing back altered data. For a reference, this is a bad idea. Hence, you mark them as type `ID` to make it clear to the client what kind of data it is. And this also means the server controls the reference so it can be changed going forward.

I don't think the specification adds more requirements on top of the type than that. In Relay, you often encode a pair of `(Type, ID)` as a base64 encoded string because that makes it easier to refetch an identifier through the `node(id: ID!)` interface. It encodes its own (globally unique) reference. But nobody forces you to use this convention in your GraphQL server.

However, I would strongly recommend using global IDs since they simplify lots of work for the client which will otherwise have to know what type it is processing.

**Comment by RPrimrose** [comment]
Thanks @jlouis , that's a great summary. My point was that it feels like that information is missing here and it's hard to tell from the spec what it means to say the IDs are "unique" and what the constraints/motivations are around that. I ended up having to piece it together from various different sources.

As a rough comparison of what might be useful, https://tools.ietf.org/html/rfc5322 for example has

> The "Message-ID:" field provides a unique message identifier that
   refers to a particular version of a particular message.  The
   uniqueness of the message identifier is guaranteed by the host that
   generates it (see below).  This message identifier is intended to be
   machine readable and not necessarily meaningful to humans.  A message
   identifier pertains to exactly one version of a particular message;
   subsequent revisions to the message each receive new message
   identifiers.

or in https://tools.ietf.org/html/rfc2616 

> An entity tag MUST be unique across all versions of all entities
   associated with a particular resource. A given entity tag value MAY
   be used for entities obtained by requests on different URIs. The use
   of the same entity tag value in conjunction with entities obtained by
   requests on different URIs does not imply the equivalence of those
   entities.

**Comment by IvanGoncharov** [comment]
@RPrimrose I agree with @jlouis it would be great to add a `Note` section similar to what was added on Int: http://facebook.github.io/graphql/draft/#sec-Int
Do you interested in creating PR for it?

**Comment by RPrimrose** [comment]
Sure, no problem. I'll stick a PR up sometime this week.

**Comment by IvanGoncharov** [comment]
@RPrimrose Ping. Do you still want to work on this PR?

**Comment by sambostock** [comment]
Is this still going to be addressed?
