### ISSUE TITLE
Having both isDeprecated and deprecationReason is redundant

### ISSUE THREAD

**Issue by swolchok** [graphql/graphql-spec#53]
Just define it so that fields are deprecated iff they have a non-null `deprecationReason`.

**Comment by leebyron** [comment]
The current reason for this is that `deprecationReason` is optional, regardless of if a field is deprecated or not, allowing a field to be tersely deprecated and avoiding less good cases like using empty strings to indicate deprecation or something along those lines.

I also felt like it was more clear to have the `isDeprecated` field, otherwise it seemed easy to misread the list of fields and assume deprecation was always possible.

If we decide to change this though, I would expect that decision to also include making `description` non-nullable. It's non-nullable for the same reason this semi-redundancy exists.

**Comment by leebyron** [comment]
Closing this aging issue.

**Comment by martinbonnin** [comment]
_necromancer_mode_on_

Can we revive this discussion? 

> allowing a field to be tersely deprecated and avoiding less good cases like using empty strings to indicate deprecation or something along those lines

Since the [current `@deprecated` directive definition](https://spec.graphql.org/draft/#sec--deprecated) has a default value, feels like terseness is not a problem anymore? One can always deprecate using just the directive:

```graphql
type Query {
  foo: Int @deprecated
}
```

We could make `reason` non-nullable in SDL:

```graphql
directive @deprecated(
  # note how reason is non-nullable here
  reason: String! = "No longer supported"
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION | ENUM_VALUE
```

This will also forbid such possibly confusing declarations:

```graphql
type Query {
  foo: Int @deprecated(reason: null) 
}
```

Introspection would keep nullable `deprecationReason`:

```graphql
type __Field {
  name: String!
  description: String
  args(includeDeprecated: Boolean = false): [__InputValue!]!
  type: __Type!
  # remove (or deprecated 😄  `isDeprecated`)
  # isDeprecated: Boolean!

  # keep the current behaviour for deprecationReason
  "the deprecation reason if the field is deprecated or null if the field is not deprecated"
  deprecationReason: String
}
```
Thoughts?

**Comment by benjie** [comment]
@martinbonnin I've re-opened this discussion; but I think the correct way forward would be to add a PR that specifically changes the `reason` argument to be non-nullable (and nothing else).
