### ISSUE TITLE
Clear-up disambiguity when using TypeExtension's and query shorthand

### ISSUE THREAD

**Issue by budde377** [graphql/graphql-spec#539]
When implementing a parser from the spec. I had a hard time deciding on the right case when certain `TypeExtension`s are used with the query operation shorthand. Namely the `EnumTypeExtension`, `InputObjectTypeExtension`, `InterfaceTypeExtension`, and `ObjectTypeExtension`. 

The issue arises with programs like the following:
```
extend interface Foo @somedir
{
  bar: String
}

```

this can according to the specification be interpreted as either 
 1. the document containing a single `InterfaceTypeExtension` with the `bar: String` field definition (and a directive), 
 2. or the document containing a `InterfaceTypeExtension` and a shorthand query with the field `String` aliased as `bar`. 

Notice that the program
```
extend interface Foo
{
  bar: String
}

```
is unequivocally a document containing a single `InterfaceTypeExtension`.

I would like to get this ambiguity cleared up and would be happy to submit a PR with the *right* solution.

**Comment by IvanGoncharov** [comment]
@budde377 sorry for delay.

GraphQL grammar is greedy that means if it will always optional tokens even if they are trailing. 

As an example take number `12`. Here is GraphQL grammar definition for integer numbers:
![image](https://user-images.githubusercontent.com/8336157/51433044-b4eb7c00-1c4a-11e9-8fef-d5145506e787.png)

First character (`1` in our example) matched by `NonZeroDidgit` but the second character (`2` in our example) could be either match by optinal `Digit` or to be intepret as next number (since spaces are insignificant in GraphQL). 
Obviously GraphQL always interpritate `12` as a single number because matching of optinal token is greedy.

Same rule works in your example and it should be always interpretated as a document contaning single interface extension.

> I would like to get this ambiguity cleared up and would be happy to submit a PR with the right solution.

AFAIK GraphQL spec never mention that grammar is gready so it would be great if you add something about it into `Apendix A`
Note: GraphQL spec already has definition for optinal token it just never state that it will always prefer longest rule:
![image](https://user-images.githubusercontent.com/8336157/51433104-1eb85580-1c4c-11e9-976c-4a61f2446790.png)

**Comment by IvanGoncharov** [comment]
Closing this since progress is tracked as #564
