### ISSUE TITLE
Feat: Return raw JSON.  Typeless Fields.  Metadata?

### ISSUE THREAD

**Issue by SephReed** [graphql/graphql-spec#612]
I have a server which I've already put a bunch of work into.  I'd like to be able to simply attach graphql where necessary to make it so it shares transformations with other endpoints.  One of these transformations is a database which stores json.  The transformation converts that json to a string and back while putting and getting from the database.

The json field I want to return is schema-less and arbitrary, so I can't make a schema for it. 

What would be nice for this is something like the "any" type in typescript.  This would allow me to pass whatever wacky value I have out through graphql, without type-checking stopping it.  This would also help for situations in which the field type might be a string or number or a date or an object or anything.

Also, use cases aside, it's important to design things with a safety release for cases where the frameworks opinion is less educated than the users.  There will always be edge cases, and giving users a way to say "trust me" is extremely important in those circumstances.

```
type Character {
  name: String!
  appearsIn: [Episode!]!
  metadata: Any
}
```

**Comment by SephReed** [comment]
And by metadata, what I'm talking about is arbitrarily added user data.  You see it a lot on apis as a way to allow users to insert things like their own personal ids, or a message to be kept alongside the item they created through the api.

**Comment by mjmahone** [comment]
This type does not belong in the spec, because using it almost always indicates a design failure. In the hundreds of times people have requested a "map"  or "JSON" or "any" type be added to our schema, I have not yet seen a compelling example where providing an unsafe response type is better than incrementally designing a specific type or set of types that are actually wanted.

If you're absolutely positive this is what you want, GraphQL servers can define their own arbitrary scalar types. I would recommend against calling the type  `Any` or `JSON` or any  other common names, just because those common names always have a non-zero chance of ending up in some future version  of the spec. So if you are completely positive you want this "any", there's nothing stopping a spec-compliant server from adding it.

From my own experience, I'd highly discourage this: if you provide a JSON type, people will start using fields returning type to hydrate their client models, at which point you lose all the safety guarantees you're trying to provide. In the future, you can silently remove a field from your JSON that clients have come to depend on, completely negating GraphQL's promise of past clients working against future servers without versioning.

**Comment by SephReed** [comment]
> GraphQL servers can define their own arbitrary scalar types

Mind sharing a link?

**Comment by mjmahone** [comment]
Yeah, here it is in the current working draft: https://graphql.github.io/graphql-spec/draft/#sel-FAHXJABABxDrS

**Comment by IvanGoncharov** [comment]
@SephReed Thanks for reporting it 👍 
We already have a proposal for adding `Any` type into spec here: https://github.com/graphql/graphql-spec/pull/325
