### ISSUE TITLE
Complex/Anonymous type declarations

### ISSUE THREAD

**Issue by vonwao** [graphql/graphql-spec#651]
I'm not submitting a detailed proposal or PR because I'm not sure if this even makes sense.  Maybe there's some other way to already alleviate my concern, which is the need of creating too many types.  

The basic problem: 
I often create a query that returns an array but has other metadata attached to that array.  So what I would like to make life is easier is something like: 
```graphql
type ReportReasons {
  category: String
  reasons: [{
    id: ID
    title: String
    body: String
  }]
}
```
Otherwise, I have to always create 2 separate types.  

Or maybe there's a way to create some kind of generic type, that I can then reuse for all queries that have a similar structure? 

How do other people deal with queries that return complex structures (like array or arrays, etc)

**Comment by benjie** [comment]
Thanks for your submission @vonwao; I don't think this feature is desirable in GraphQL. All object types in GraphQL are named - if they're not named then we cannot apply fragments against them (and fragments are one of the most important features of GraphQL IMO).

I would express the above with a re-usable `Reason` type:

```graphql
type Reason {
  id: ID
  title: String
  body: String
}

type ReportReasons {
  category: String
  reasons: [Reason]
}
```

I don't think that the correct way to solve "too many types" is to add nested anonymous types. Anonymous types could actually increase the number of underlying types in the schema (because reuse would go down), makes it harder to refer to these types, and would make schemas a lot harder to reason about IMO. Adding anonymous types would also reduce the places where we can apply documentation, directives, and other such concerns.

**Comment by michaelstaib** [comment]
I agree with @benjie. Having anonymous types does not really solve anything but introduces a lot of headaches with fragments and other things. Also there are a lot of other issues that I see with interfaces, directives and arguments on those types.

**Comment by sungam3r** [comment]
What are anonymous types for? As a rule, they were invented so that you can quickly make a container for simple values (properties) and use it without a type declaration. For example, LINQ in .NET. The whole point of SDL is in the API declaration. This is simply not the place where anonymous types will bring at least some benefit.

**Comment by vonwao** [comment]
Well, they wouldn't have to be anonymous exactly.  They could have a type, that uses the parent type as a namespace, so the type of the nested array could be referenced as ReportReasons.reasons.  I think my main point is why should we need an explosion of names to deal with complex data structures?

**Comment by vonwao** [comment]
The same goes for queries and mutations.  Maybe the types of input and result time of them could be accessed like SomeQuery._InputType and SomeQuery._ResultType or something like that.  Again, I'm not sure if it's a great idea.  But it could make the problem of having way too many names in a schema more manageable. 

Because: "There are only two hard things in Computer Science: cache invalidation and naming things."

**Comment by mike-marcacci** [comment]
@vonwao you're describing a scenario that a lot of us have encountered when begging to work with GraphQL. We are used to modeling data with arbitrary depth in our REST APIs, and we don't like having to attribute the same "importance" to these "auxiliary types" by actually _naming them_.

I get that. However, I can promise you that as your schema evolves, having a name for types you previously though of as disposable will prove valuable. Keep in mind that GraphQL is a spec for API's and _not_ a single implementation: each new piece of complexity or "way to do things" must be solved in hundreds of different libraries written in dozens of different languages by dozens of different maintainers. A "name" with its current character limitations is a pretty core assumption at the moment.

I suspect that as you continue "thinking in GraphQL," writing type names will feel more and more natural, and will help guide your schema design. For example, based only on your initial example, I suspect you may want types `Report`, `ReportReason`, and `Reason` (I have yet to find a good case for naming a type with a _plural_).

**Comment by paulmil1** [comment]
no annonymous types? wait what? this is ridiculous!

**Comment by sungam3r** [comment]
>  this is ridiculous!

This is GraphQL!

**Comment by IvanGoncharov** [comment]
@benjie @mike-marcacci @sungam3r @vonwao Thanks for providing a detailed explanation.

Anonymous types contradict `Simplicity and consistency over expressiveness and terseness` guiding principle:
> There are plenty of behaviors and patterns found in other languages intentionally absent from GraphQL. "Possible but awkward" is often favored over more complex alternatives. Simplicity (e.g. fewer concepts) is more important than expressing more sophisticated ideas or writing less.
